buildbot-worker: Remove setuptools from virtualenv due to py3 failure
For whatever reason this failed with python3:

 Collecting setuputils
  Using cached https://files.pythonhosted.org/packages/a1/7a/3e1ae654321f3a672efdbd129af083bf26b4419db42485b63ea862bdfcac/setuputils-0.9.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File \"<string>\", line 1, in <module>
      File \"/tmp/pip-install-xvb9htx4/setuputils/setup.py\", line 38, in <module>
        from setuputils import convert_md_to_rst, setup_vars
      File \"/tmp/pip-install-xvb9htx4/setuputils/setuputils.py\", line 62, in <module>
        from itertools import chain, dropwhile, islice, izip, takewhile
    ImportError: cannot import name 'izip'

However, if setuputils is needed on py2, then it should be pulled in as
a dependency, no?